### PR TITLE
Visitor pattern slides.

### PR DESCRIPTION
**Pull request by sagark4**
Added my slides; the book content is under CC non-commercial no-derivatives license, so I am able to use them.

### CODE REVIEW

**Comment by chrysn** [comment]
Both the book and Wikipedia references are declared clearly as sources, and while it doesn't explicitly state the license there, I'd take that as sufficient indication that something else than the otherwise default MIT of this repository applies. Thanks, merging.

**Comment by sagark4** [comment]
Thanks.  Yeah, not sure if it's MIT because the book is CC, non-commercial,
non-derivative.  I hope it's okay to have non MIT stuff in there.

**Comment by sagark4** [comment]
I just saw at the home page of this repo that I should have provided a separate .license file or mention that it is something other than MIT in my pdf.  Should I do that in a separate PR?  Sorry about the confusion.

**Comment by sagark4** [comment]
@chrysn Sorry again for being pedantic, but the repo readme implies that some stuff is allowed to be non-MIT whereas [the license](https://github.com/RustVienna/meetup-history/blob/master/LICENSE) itself does not say this.  Maybe we can update the license mentioning that the MIT license applies to the files that do not mention copyright or licensing info.  I am happy to create a PR where I handle this as well as update my slides with more concrete licensing as I mentioned in the previous message, if you'd like.

**Comment by chrysn** [comment]
The README says it's fine to have non-MIT content as long as it is indicated that the default terms do not apply. While having a source attribution (the book, Wikipedia) is not overly explicit, I think it's clear from the context that different terms apply there.

The LICENSE file is just the referenced license; its presence in a repository doesn't semantically indicate comprehensiveness, that's what copyright statements on files, in prose ("license X as defined in file Y applies"; LICENSE files themselves make no claim as to which files they pertain to).

The IMO cleanest way to express all this would be to consequently apply https://reuse.software/ guidlines, but sadly too few people care. The hint in the README file to make an explicit statement or add a .license file is a clue to that, but not a very explicit one. I've prepared https://github.com/RustVienna/meetup-history/pull/14, could you give that a short review and tell if this would have clarified the items that are coming up in this issue?

**Comment by sagark4** [comment]
I am not an expert but just someone who likes to play it safe.  Personally for me, adding the second paragraph or something to that effect would more than suffice.  But if this is just common knowledge, then obviously ignore me.  :-)

**Comment by sagark4** [comment]
I am not an expert but just someone who likes to play it safe. Personally for me, adding the second paragraph or something to that effect would more than suffice. But if this is just common knowledge, then obviously ignore me. :-)

> The LICENSE file is just the referenced license; its presence in a repository doesn't semantically indicate comprehensiveness, that's what copyright statements on files, in prose ("license X as defined in file Y applies"; LICENSE files themselves make no claim as to which files they pertain to).

I briefly looked at the reuse.software guideline.  Since I _do_ care about these things, I will update my slides and also add a license file in a separate PR.  I understand that my slides are almost trivial where everything is justified to be used under the fair-use clause, still for me it's a good exercise.

**Comment by chrysn** [comment]
At that level of being technical, fair use is a term of US copyright, and there is no similar clause in European copyright (or there was not; I'm not up to date with the latest versions). Usually not an issue in the software area when one only concerns themselves with the license of the source (when the built item is not distributed; in software, I'd distribute my source, the CC-NC-ND blob and a build script). What saves this case (and is why I merged this right away) in my understanding is that it's a declared quote of an image and thus should be [covered](https://de.wikipedia.org/wiki/Bildzitat).

**Comment by sagark4** [comment]
Interesting!  Then fyi that the pastry code is taken from the book as well and I don't explicitly cite it (only at the beginning that most slides are based on the book...).  The rest of the stuff from the book is [MIT licensed](https://github.com/munificent/craftinginterpreters/blob/master/LICENSE).  But yeah, as you said, the original CC-NC-ND license explicitly mentions fair use, which is in the American context.

**Pull request merged**
